pipeline:
  build:
    when:
      event: push
    image: 1and1internet/template-library-tools
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - python3 -u /scripts/images/build.py

  spectests:
    when:
      event: push
    image: 1and1internet/ubuntu-16-rspec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make do-test IMAGE_NAME=build-${CI_REPO#*/}-${CI_BUILD_NUMBER}/${CI_REPO#*/}

  publish:
    when:
      event: push
    image: 1and1internet/template-library-tools
    volumes:
      - /secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
      - /shared_storage:/tmp/image-comparison
    commands:
     - python3 -u /scripts/images/publish.py
